---
- name: Install required packaes for plugins
  apt:
    name:
      - autoconf
      - build-essential
      - unzip
      - openssl
      - libapache2-mod-php
      - apache2
      - unzip
      - php
      - python3
      - python3-pip
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install passlib
  pip:
    name: passlib

- name: nagios directory
  file:
    path: ~/nagios
    state: directory

- name: Download Nagios core
  unarchive:
    src: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
    dest: ~/nagios
    remote_src: yes
    mode: 0777
    owner: root
    group: root

- name: Compile and install nagios core
  shell: |
    cd ~/nagios.nagioscore-*
    sudo ./configure --with-httpd-conf=/etc/apache2/sites-enabled
    sudo make all
    sudo make install-groups-users
    sudo usermod - a -G nagios apache
    sudo make install
    sudo make install-daemoninit
    sudo make install-commandmode
    sudo make install-config
    sudo make install-webconf
    sudo a2enmod rewrite
    sudo a2enmod cgi

- name: Download Plugins
  unarchive:
    src: https://github.com/nagios-plugins/nagios-plugins/archive/release-2.3.3.tar.gz
    dest: ~/nagios
    remote_src: yes
    mode: 0777
    owner: root
    group: root

- name: Compile and install plugins
  shell: |
    cd ~/nagios/nagios-plugins*
    ./tools/setup
    ./configure
    make
    make install

- name: start Nagios
  service:
    name: nagios
    enabled: true
    state: restarted

- name: start apache
  service:
    name: apache2
    state: started
    enabled: true
