- name: dependecies
  apt:
    name:
      - apache2
      - mysql-server
      - php-mysql
      - php
      - libapache2-mod-php
    state: latest

- name: Start apache 2
  service:
    name: apache2
    state: started
    enabled: true
